// Package security is func library that implement security standard.
// # This manifest was generated by ymir. DO NOT EDIT.
package security

import (
	"crypto/rand"
	"time"

	"github.com/oklog/ulid/v2"
)

var (
	entropy = rand.Reader
	now     = time.Now()
)

func GenID() (string, error) {
	id, err := ulid.New(ulid.Timestamp(now), entropy)
	if err != nil {
		return "", err
	}
	return id.String(), nil
}
