// Package shared is library function for whole system.
// # This manifest was generated by ymir. DO NOT EDIT.
package shared

import (
	"context"
	"errors"

	"github.com/rs/zerolog/log"

	"gitlab.playcourt.id/dedenurr12/ymirblog/pkg/infrastructure"
)

// Graceful is the loop main module.
func Graceful(
	stopCh <-chan struct{},
	errCh <-chan error,
	fn func(ctx context.Context)) error {
	ctx, cancel := context.WithTimeout(context.Background(), infrastructure.Envs.Server.Timeout)
	defer cancel()
	for { // wait for SIGTERM or SIGINT
		select {
		case <-stopCh:
			fn(ctx)
			log.Error().Err(errors.New("interrupt received, shutting down")).
				Msg("Server interrupted through context")
			return nil
		case err := <-errCh:
			fn(ctx)
			log.Error().Err(err).Msg("Server interrupted through error channel")
			return err
		}
	}
}
